"use client"

export {
  DashboardLayoutRoot,
  DashboardLayoutContentShell,
  DashboardLayoutContent,
  DashboardLayoutStickyContentHeaderContainer,
  DashboardLayoutContentHeader,
  DashboardLayoutContentActions,
  DashboardLayoutStickyDetailHeader,
  DashboardLayoutStickyDetailHeaderIcon,
  DashboardLayoutStickyDetailHeaderTitle,
  DashboardLayoutStickyDetailHeaderDescription,
  DashboardLayoutStickyDetailActions,
  DashboardLayoutSidebar,
  DashboardLayoutSidebarDropdown,
  DashboardLayoutSidebarGroup,
  DashboardLayoutSidebarItem,
  DashboardLayoutSidebarFooter,
  DashboardLayoutFooterNotes,
  DashboardLayoutFooterNotesLinkGroup,
  DashboardLayoutFooterNotesLink,
  Root,
  ContentShell,
  Content,
  StickyContentHeaderContainer,
  ContentHeader,
  ContentActions,
  StickyDetailHeader,
  StickyDetailHeaderIcon,
  StickyDetailHeaderTitle,
  StickyDetailHeaderDescription,
  StickyDetailActions,
  Sidebar,
  SidebarDropdown,
  SidebarGroup,
  SidebarItem,
  SidebarFooter,
  FooterNotes,
  FooterNotesLinkGroup,
  FooterNotesLink,
} from "./dashboard-layout"
